namespace AndroidNDKBinding
{
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct JNINativeInterface
    {
        public void* reserved0;
        public void* reserved1;
        public void* reserved2;
        public void* reserved3;
        public delegate* unmanaged<_JNIEnv*, int> * GetVersion;
        public delegate* unmanaged<_JNIEnv*, byte*, _jobject*, sbyte*, int, _jclass*> * DefineClass;
        public delegate* unmanaged<_JNIEnv*, byte*, _jclass*> * FindClass;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*> * FromReflectedMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*> * FromReflectedField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, byte, _jobject*> * ToReflectedMethod;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jclass*> * GetSuperclass;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jclass*, byte> * IsAssignableFrom;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, byte, _jobject*> * ToReflectedField;
        public delegate* unmanaged<_JNIEnv*, _jthrowable*, int> * Throw;
        public delegate* unmanaged<_JNIEnv*, _jclass*, byte*, int> * ThrowNew;
        public delegate* unmanaged<_JNIEnv*, _jthrowable*> * ExceptionOccurred;
        public delegate* unmanaged<_JNIEnv*, void> * ExceptionDescribe;
        public delegate* unmanaged<_JNIEnv*, void> * ExceptionClear;
        public delegate* unmanaged<_JNIEnv*, byte*, void> * FatalError;
        public delegate* unmanaged<_JNIEnv*, int, int> * PushLocalFrame;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jobject*> * PopLocalFrame;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jobject*> * NewGlobalRef;
        public delegate* unmanaged<_JNIEnv*, _jobject*, void> * DeleteGlobalRef;
        public delegate* unmanaged<_JNIEnv*, _jobject*, void> * DeleteLocalRef;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jobject*, byte> * IsSameObject;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jobject*> * NewLocalRef;
        public delegate* unmanaged<_JNIEnv*, int, int> * EnsureLocalCapacity;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jobject*> * AllocObject;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, _jobject*> * NewObject;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, byte*, _jobject*> * NewObjectV;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, jvalue*, _jobject*> * NewObjectA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*> * GetObjectClass;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, byte> * IsInstanceOf;
        public delegate* unmanaged<_JNIEnv*, _jclass*, byte*, byte*, _jmethodID*> * GetMethodID;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, _jobject*> * CallObjectMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, byte*, _jobject*> * CallObjectMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, jvalue*, _jobject*> * CallObjectMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, byte> * CallBooleanMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, byte*, byte> * CallBooleanMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, jvalue*, byte> * CallBooleanMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, sbyte> * CallByteMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, byte*, sbyte> * CallByteMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, jvalue*, sbyte> * CallByteMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, ushort> * CallCharMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, byte*, ushort> * CallCharMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, jvalue*, ushort> * CallCharMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, short> * CallShortMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, byte*, short> * CallShortMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, jvalue*, short> * CallShortMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, int> * CallIntMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, byte*, int> * CallIntMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, jvalue*, int> * CallIntMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, long> * CallLongMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, byte*, long> * CallLongMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, jvalue*, long> * CallLongMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, float> * CallFloatMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, byte*, float> * CallFloatMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, jvalue*, float> * CallFloatMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, double> * CallDoubleMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, byte*, double> * CallDoubleMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, jvalue*, double> * CallDoubleMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, void> * CallVoidMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, byte*, void> * CallVoidMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jmethodID*, jvalue*, void> * CallVoidMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, _jobject*> * CallNonvirtualObjectMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, byte*, _jobject*> * CallNonvirtualObjectMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue*, _jobject*> * CallNonvirtualObjectMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, byte> * CallNonvirtualBooleanMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, byte*, byte> * CallNonvirtualBooleanMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue*, byte> * CallNonvirtualBooleanMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, sbyte> * CallNonvirtualByteMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, byte*, sbyte> * CallNonvirtualByteMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue*, sbyte> * CallNonvirtualByteMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, ushort> * CallNonvirtualCharMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, byte*, ushort> * CallNonvirtualCharMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue*, ushort> * CallNonvirtualCharMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, short> * CallNonvirtualShortMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, byte*, short> * CallNonvirtualShortMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue*, short> * CallNonvirtualShortMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, int> * CallNonvirtualIntMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, byte*, int> * CallNonvirtualIntMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue*, int> * CallNonvirtualIntMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, long> * CallNonvirtualLongMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, byte*, long> * CallNonvirtualLongMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue*, long> * CallNonvirtualLongMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, float> * CallNonvirtualFloatMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, byte*, float> * CallNonvirtualFloatMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue*, float> * CallNonvirtualFloatMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, double> * CallNonvirtualDoubleMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, byte*, double> * CallNonvirtualDoubleMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue*, double> * CallNonvirtualDoubleMethodA;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, void> * CallNonvirtualVoidMethod;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, byte*, void> * CallNonvirtualVoidMethodV;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue*, void> * CallNonvirtualVoidMethodA;
        public delegate* unmanaged<_JNIEnv*, _jclass*, byte*, byte*, _jfieldID*> * GetFieldID;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, _jobject*> * GetObjectField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, byte> * GetBooleanField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, sbyte> * GetByteField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, ushort> * GetCharField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, short> * GetShortField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, int> * GetIntField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, long> * GetLongField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, float> * GetFloatField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, double> * GetDoubleField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, _jobject*, void> * SetObjectField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, byte, void> * SetBooleanField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, sbyte, void> * SetByteField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, ushort, void> * SetCharField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, short, void> * SetShortField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, int, void> * SetIntField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, long, void> * SetLongField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, float, void> * SetFloatField;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jfieldID*, double, void> * SetDoubleField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, byte*, byte*, _jmethodID*> * GetStaticMethodID;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, _jobject*> * CallStaticObjectMethod;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, byte*, _jobject*> * CallStaticObjectMethodV;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, jvalue*, _jobject*> * CallStaticObjectMethodA;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, byte> * CallStaticBooleanMethod;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, byte*, byte> * CallStaticBooleanMethodV;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, jvalue*, byte> * CallStaticBooleanMethodA;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, sbyte> * CallStaticByteMethod;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, byte*, sbyte> * CallStaticByteMethodV;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, jvalue*, sbyte> * CallStaticByteMethodA;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, ushort> * CallStaticCharMethod;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, byte*, ushort> * CallStaticCharMethodV;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, jvalue*, ushort> * CallStaticCharMethodA;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, short> * CallStaticShortMethod;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, byte*, short> * CallStaticShortMethodV;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, jvalue*, short> * CallStaticShortMethodA;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, int> * CallStaticIntMethod;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, byte*, int> * CallStaticIntMethodV;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, jvalue*, int> * CallStaticIntMethodA;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, long> * CallStaticLongMethod;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, byte*, long> * CallStaticLongMethodV;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, jvalue*, long> * CallStaticLongMethodA;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, float> * CallStaticFloatMethod;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, byte*, float> * CallStaticFloatMethodV;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, jvalue*, float> * CallStaticFloatMethodA;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, double> * CallStaticDoubleMethod;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, byte*, double> * CallStaticDoubleMethodV;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, jvalue*, double> * CallStaticDoubleMethodA;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, void> * CallStaticVoidMethod;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, byte*, void> * CallStaticVoidMethodV;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jmethodID*, jvalue*, void> * CallStaticVoidMethodA;
        public delegate* unmanaged<_JNIEnv*, _jclass*, byte*, byte*, _jfieldID*> * GetStaticFieldID;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, _jobject*> * GetStaticObjectField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, byte> * GetStaticBooleanField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, sbyte> * GetStaticByteField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, ushort> * GetStaticCharField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, short> * GetStaticShortField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, int> * GetStaticIntField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, long> * GetStaticLongField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, float> * GetStaticFloatField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, double> * GetStaticDoubleField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, _jobject*, void> * SetStaticObjectField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, byte, void> * SetStaticBooleanField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, sbyte, void> * SetStaticByteField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, ushort, void> * SetStaticCharField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, short, void> * SetStaticShortField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, int, void> * SetStaticIntField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, long, void> * SetStaticLongField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, float, void> * SetStaticFloatField;
        public delegate* unmanaged<_JNIEnv*, _jclass*, _jfieldID*, double, void> * SetStaticDoubleField;
        public delegate* unmanaged<_JNIEnv*, ushort*, int, _jstring*> * NewString;
        public delegate* unmanaged<_JNIEnv*, _jstring*, int> * GetStringLength;
        public delegate* unmanaged<_JNIEnv*, _jstring*, byte*, ushort*> * GetStringChars;
        public delegate* unmanaged<_JNIEnv*, _jstring*, ushort*, void> * ReleaseStringChars;
        public delegate* unmanaged<_JNIEnv*, byte*, _jstring*> * NewStringUTF;
        public delegate* unmanaged<_JNIEnv*, _jstring*, int> * GetStringUTFLength;
        public delegate* unmanaged<_JNIEnv*, _jstring*, byte*, byte*> * GetStringUTFChars;
        public delegate* unmanaged<_JNIEnv*, _jstring*, byte*, void> * ReleaseStringUTFChars;
        public delegate* unmanaged<_JNIEnv*, _jarray*, int> * GetArrayLength;
        public delegate* unmanaged<_JNIEnv*, int, _jclass*, _jobject*, _jobjectArray*> * NewObjectArray;
        public delegate* unmanaged<_JNIEnv*, _jobjectArray*, int, _jobject*> * GetObjectArrayElement;
        public delegate* unmanaged<_JNIEnv*, _jobjectArray*, int, _jobject*, void> * SetObjectArrayElement;
        public delegate* unmanaged<_JNIEnv*, int, _jbooleanArray*> * NewBooleanArray;
        public delegate* unmanaged<_JNIEnv*, int, _jbyteArray*> * NewByteArray;
        public delegate* unmanaged<_JNIEnv*, int, _jcharArray*> * NewCharArray;
        public delegate* unmanaged<_JNIEnv*, int, _jshortArray*> * NewShortArray;
        public delegate* unmanaged<_JNIEnv*, int, _jintArray*> * NewIntArray;
        public delegate* unmanaged<_JNIEnv*, int, _jlongArray*> * NewLongArray;
        public delegate* unmanaged<_JNIEnv*, int, _jfloatArray*> * NewFloatArray;
        public delegate* unmanaged<_JNIEnv*, int, _jdoubleArray*> * NewDoubleArray;
        public delegate* unmanaged<_JNIEnv*, _jbooleanArray*, byte*, byte*> * GetBooleanArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jbyteArray*, byte*, sbyte*> * GetByteArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jcharArray*, byte*, ushort*> * GetCharArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jshortArray*, byte*, short*> * GetShortArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jintArray*, byte*, int*> * GetIntArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jlongArray*, byte*, long*> * GetLongArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jfloatArray*, byte*, float*> * GetFloatArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jdoubleArray*, byte*, double*> * GetDoubleArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jbooleanArray*, byte*, int, void> * ReleaseBooleanArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jbyteArray*, sbyte*, int, void> * ReleaseByteArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jcharArray*, ushort*, int, void> * ReleaseCharArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jshortArray*, short*, int, void> * ReleaseShortArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jintArray*, int*, int, void> * ReleaseIntArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jlongArray*, long*, int, void> * ReleaseLongArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jfloatArray*, float*, int, void> * ReleaseFloatArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jdoubleArray*, double*, int, void> * ReleaseDoubleArrayElements;
        public delegate* unmanaged<_JNIEnv*, _jbooleanArray*, int, int, byte*, void> * GetBooleanArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jbyteArray*, int, int, sbyte*, void> * GetByteArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jcharArray*, int, int, ushort*, void> * GetCharArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jshortArray*, int, int, short*, void> * GetShortArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jintArray*, int, int, int*, void> * GetIntArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jlongArray*, int, int, long*, void> * GetLongArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jfloatArray*, int, int, float*, void> * GetFloatArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jdoubleArray*, int, int, double*, void> * GetDoubleArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jbooleanArray*, int, int, byte*, void> * SetBooleanArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jbyteArray*, int, int, sbyte*, void> * SetByteArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jcharArray*, int, int, ushort*, void> * SetCharArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jshortArray*, int, int, short*, void> * SetShortArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jintArray*, int, int, int*, void> * SetIntArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jlongArray*, int, int, long*, void> * SetLongArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jfloatArray*, int, int, float*, void> * SetFloatArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jdoubleArray*, int, int, double*, void> * SetDoubleArrayRegion;
        public delegate* unmanaged<_JNIEnv*, _jclass*, JNINativeMethod*, int, int> * RegisterNatives;
        public delegate* unmanaged<_JNIEnv*, _jclass*, int> * UnregisterNatives;
        public delegate* unmanaged<_JNIEnv*, _jobject*, int> * MonitorEnter;
        public delegate* unmanaged<_JNIEnv*, _jobject*, int> * MonitorExit;
        public delegate* unmanaged<_JNIEnv*, _JavaVM**, int> * GetJavaVM;
        public delegate* unmanaged<_JNIEnv*, _jstring*, int, int, ushort*, void> * GetStringRegion;
        public delegate* unmanaged<_JNIEnv*, _jstring*, int, int, byte*, void> * GetStringUTFRegion;
        public delegate* unmanaged<_JNIEnv*, _jarray*, byte*, void*> * GetPrimitiveArrayCritical;
        public delegate* unmanaged<_JNIEnv*, _jarray*, void*, int, void> * ReleasePrimitiveArrayCritical;
        public delegate* unmanaged<_JNIEnv*, _jstring*, byte*, ushort*> * GetStringCritical;
        public delegate* unmanaged<_JNIEnv*, _jstring*, ushort*, void> * ReleaseStringCritical;
        public delegate* unmanaged<_JNIEnv*, _jobject*, _jobject*> * NewWeakGlobalRef;
        public delegate* unmanaged<_JNIEnv*, _jobject*, void> * DeleteWeakGlobalRef;
        public delegate* unmanaged<_JNIEnv*, byte> * ExceptionCheck;
        public delegate* unmanaged<_JNIEnv*, void*, long, _jobject*> * NewDirectByteBuffer;
        public delegate* unmanaged<_JNIEnv*, _jobject*, void*> * GetDirectBufferAddress;
        public delegate* unmanaged<_JNIEnv*, _jobject*, long> * GetDirectBufferCapacity;
        public delegate* unmanaged<_JNIEnv*, _jobject*, jobjectRefType> * GetObjectRefType;
    }
}